spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/article_cms
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:7734}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb