spring:
  datasource:
    url: jdbc:mysql://localhost:3306/article_cms
    username: root
    password: 7734

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb